### ISSUE TITLE
Passing argument as string fails

### ISSUE THREAD

**Issue by Willianvdv** [stripe/subprocess#14]
```
[1] pry(main)> Subprocess.check_output ['echo', 1]
/Users/willian/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/subprocess-bec731f04198/lib/subprocess.rb:287:in `dump': no _dump_data is defined for class Binding (TypeError)
ArgumentError: marshal data too short
from /Users/willian/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.2/lib/active_support/core_ext/marshal.rb:6:in `load'
[2] pry(main)> Subprocess.check_output ['echo', '1']
=> "1\n"
```

**Comment by Willianvdv** [comment]
Awesome gem btw!

**Comment by zenazn** [comment]
Err, this suggests that passing arguments as non-strings fails? That is expected behavior, although the error message for that is a bit wonky

**Comment by Willianvdv** [comment]
cool!
